---
# tasks file for iris
- name: copy Iris templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/irisinstall", dest: "/tmp/irisinstall", mode: "0744" }
     - { src: "templates/iris.service", dest: "/usr/lib/systemd/system/iris.service", mode: "0444" }

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: files/IRIS_Community-2020.1.1.408.0-lnxrhx64.tar.g
    dest: /tmp


- name: "Change shared memory settings"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'kernel.shmall', value: '2097152' }
    - { name: 'kernel.shmmax', value: '333554432' }

- name: "Add the management group user"
  user:
   name: "{{ mangrp }}"
   state: "present"

- name: "Run the Iris install script"
  command: "/tmp/irisinstall {{ platform }}"
  notify:
    - Reload the systemd service daemon
    - restart iris


- name: Copy the Cache key file
  copy:
     src: "{{ key_loc }}"
     dest: "{{ inst_dir }}/mgr/cache.key"
  when: 
   - key_bool=="Y" 
 

