---
# tasks file for iris
- name: copy Iris templates
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     mode: "{{ item.mode }}"
  loop:
     - { src: "templates/irisinstall", dest: "/tmp/irisinstall", mode: "0744" }
     - { src: "templates/iris.service", dest: "/usr/lib/systemd/system/iris.service", mode: "0444" }
- name: Extract IRIS installation media
  unarchive:
    src: "files/{{ inst_tar }}"
    dest: /tmp
- name: "Change shared memory settings"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'kernel.shmall', value: '2097152' }
    - { name: 'kernel.shmmax', value: '333554432' }
- name: "Add users for installaton"
  user:
   name: "{{ item }}"
   state: "present"
  loop:
    - "{{ manusr }}"
    - "{{ irisusr }}"
- name: "Add groups for installaton"
  group:
   name: "{{ item }}"
   state: "present"
  loop:
    - "{{ mangrp }}"
    - "{{ irisgrp }}"
- name: "Run the Iris install script"
  command: "/tmp/irisinstall"
  notify:
    - Reload the systemd service daemon
    - restart iris
  register: cmd
  changed_when: cmd_end is not search("")
