---
# handlers file for iris
- name: Reload the systemd service daemon
  command: "systemctl daemon-reload"
  tags:
  - skip_ansible_lint # Had to use systemctl as systemd module waasn't loading changes correctly
- name: restart iris
  service:
     name: iris
     state: restarted
     enabled: "yes"
