#!/bin/bash
cd "/tmp/IRIS_Community-2020.1.1.408.0-lnxrhx64"
export ISC_PACKAGE_PLATFORM="{{ platform }}"
export ISC_PACKAGE_INSTANCENAME="{{ instname }}"
export ISC_PACKAGE_INSTALLDIR="{{ inst_dir }}"
export ISC_PACKAGE_INITIAL_SECURITY="{{ sec }}"
export ISC_PACKAGE_MGRGROUP="{{ mangrp }}"
export ISC_PACKAGE_MGRUSER="{{ manusr }}"
export ISC_PACKAGE_IRISUSER="{{ irisusr }}"
export ISC_PACKAGE_IRISGROUP="{{ irisgrp }}"
export ISC_PACKAGE_CSPSYSTEM_PASSWORD="{{ csppass }}"
export ISC_PACKAGE_USER_PASSWORD="{{ userpass }}"
export ISC_PACKAGE_STARTIRIS="N"
sleep 1;./irisinstall_silent
